spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_test_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: generate-schema
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
